// Code generated by "stringer -type PID"; DO NOT EDIT.

package ardilla

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StreamDeckMini-99]
	_ = x[StreamDeckMiniV2-144]
	_ = x[StreamDeckOriginal-96]
	_ = x[StreamDeckOriginalV2-109]
	_ = x[StreamDeckMK2-128]
	_ = x[StreamDeckXL-108]
	_ = x[StreamDeckPedal-134]
}

const (
	_PID_name_0 = "StreamDeckOriginal"
	_PID_name_1 = "StreamDeckMini"
	_PID_name_2 = "StreamDeckXLStreamDeckOriginalV2"
	_PID_name_3 = "StreamDeckMK2"
	_PID_name_4 = "StreamDeckPedal"
	_PID_name_5 = "StreamDeckMiniV2"
)

var (
	_PID_index_2 = [...]uint8{0, 12, 32}
)

func (i PID) String() string {
	switch {
	case i == 96:
		return _PID_name_0
	case i == 99:
		return _PID_name_1
	case 108 <= i && i <= 109:
		i -= 108
		return _PID_name_2[_PID_index_2[i]:_PID_index_2[i+1]]
	case i == 128:
		return _PID_name_3
	case i == 134:
		return _PID_name_4
	case i == 144:
		return _PID_name_5
	default:
		return "PID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
